"""reference intake and session ownership

Revision ID: 0266ce26f85b
Revises: f8065ed9b5a4
Create Date: 2026-08-24 19:04:52.364390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0266ce26f85b'
down_revision: Union[str, None] = 'f8065ed9b5a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_briefs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('design_request_id', sa.UUID(), nullable=False),
    sa.Column('request_type', sa.String(length=40), nullable=False),
    sa.Column('customer_message', sa.Text(), nullable=True),
    sa.Column('confirmed_text', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('product_type', sa.String(length=40), nullable=True),
    sa.Column('material_preference', sa.String(length=40), nullable=True),
    sa.Column('style_intent', sa.String(length=40), nullable=True),
    sa.Column('reference_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generation_hints', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('deadline', sa.String(length=40), nullable=True),
    sa.Column('delivery_emirate', sa.String(length=40), nullable=True),
    sa.Column('missing_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['design_request_id'], ['design_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('design_request_id')
    )
    op.create_table('reference_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('design_request_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('media_type', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('provenance', sa.String(length=32), nullable=False),
    sa.Column('ip_risk', sa.String(length=32), nullable=False),
    sa.Column('privacy_status', sa.String(length=24), nullable=False),
    sa.Column('scan_status', sa.String(length=24), nullable=False),
    sa.Column('analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['design_request_id'], ['design_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reference_assets_design_request_id'), 'reference_assets', ['design_request_id'], unique=False)
    op.add_column('design_requests', sa.Column('session_token_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_design_requests_session_token_hash'), 'design_requests', ['session_token_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_design_requests_session_token_hash'), table_name='design_requests')
    op.drop_column('design_requests', 'session_token_hash')
    op.drop_index(op.f('ix_reference_assets_design_request_id'), table_name='reference_assets')
    op.drop_table('reference_assets')
    op.drop_table('customer_briefs')
    # ### end Alembic commands ###
