"""text geometry and quality report columns

Revision ID: 93c0fd7c220a
Revises: 0266ce26f85b
Create Date: 2026-08-24 19:37:01.468768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '93c0fd7c220a'
down_revision: Union[str, None] = '0266ce26f85b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('design_candidates', sa.Column('text_geometry_wkt', sa.Text(), nullable=True))
    op.add_column('design_candidates', sa.Column('quality_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('design_versions', sa.Column('text_geometry_wkt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('design_versions', 'text_geometry_wkt')
    op.drop_column('design_candidates', 'quality_report')
    op.drop_column('design_candidates', 'text_geometry_wkt')
    # ### end Alembic commands ###
