"""ai generations

Revision ID: 9520aa9396f0
Revises: 8f88bb06552a
Create Date: 2026-08-25 00:01:11.996315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '9520aa9396f0'
down_revision: Union[str, None] = '8f88bb06552a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_generations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('design_request_id', sa.UUID(), nullable=False),
    sa.Column('design_version_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('provider', sa.String(length=48), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('visual_brief', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('geometry_hash', sa.String(length=64), nullable=False),
    sa.Column('source_text_sha256', sa.String(length=64), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=True),
    sa.Column('content_sha256', sa.String(length=64), nullable=True),
    sa.Column('guard_status', sa.String(length=32), nullable=False),
    sa.Column('guard_report', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('quality', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['design_request_id'], ['design_requests.id'], ),
    sa.ForeignKeyConstraint(['design_version_id'], ['design_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_generations_cache_key'), 'ai_generations', ['cache_key'], unique=False)
    op.create_index(op.f('ix_ai_generations_design_request_id'), 'ai_generations', ['design_request_id'], unique=False)
    op.create_index(op.f('ix_ai_generations_design_version_id'), 'ai_generations', ['design_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_generations_design_version_id'), table_name='ai_generations')
    op.drop_index(op.f('ix_ai_generations_design_request_id'), table_name='ai_generations')
    op.drop_index(op.f('ix_ai_generations_cache_key'), table_name='ai_generations')
    op.drop_table('ai_generations')
    # ### end Alembic commands ###
