"""initial persistence schema

Revision ID: f8065ed9b5a4
Revises: 
Create Date: 2026-08-24 18:45:27.724449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f8065ed9b5a4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('design_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('source_text_raw', sa.Text(), nullable=False),
    sa.Column('source_text_normalized', sa.Text(), nullable=False),
    sa.Column('source_text_sha256', sa.String(length=64), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('product_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('ranking_config_version', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('font_references',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('font_id', sa.String(length=64), nullable=False),
    sa.Column('family', sa.String(length=120), nullable=False),
    sa.Column('license', sa.String(length=120), nullable=False),
    sa.Column('rights_status', sa.String(length=32), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('registry_version', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('font_id', 'file_sha256')
    )
    op.create_table('design_candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('candidate_key', sa.String(length=32), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('recipe', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('identity_verified', sa.Boolean(), nullable=False),
    sa.Column('validation_passed', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ranking_config_version', sa.String(length=16), nullable=False),
    sa.Column('diversity_rank', sa.Integer(), nullable=True),
    sa.Column('geometry_wkt', sa.Text(), nullable=False),
    sa.Column('source_text_sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['design_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id', 'candidate_key')
    )
    op.create_index(op.f('ix_design_candidates_request_id'), 'design_candidates', ['request_id'], unique=False)
    op.create_table('designs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('selected_candidate_id', sa.UUID(), nullable=False),
    sa.Column('current_version_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['design_requests.id'], ),
    sa.ForeignKeyConstraint(['selected_candidate_id'], ['design_candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('design_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('design_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('parent_version_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('immutable_source_text', sa.Text(), nullable=False),
    sa.Column('source_text_sha256', sa.String(length=64), nullable=False),
    sa.Column('geometry_wkt', sa.Text(), nullable=False),
    sa.Column('geometry_hash', sa.String(length=64), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('arabic_engine_version', sa.String(length=16), nullable=False),
    sa.Column('font_id', sa.String(length=64), nullable=False),
    sa.Column('font_version', sa.String(length=64), nullable=False),
    sa.Column('recipe_id', sa.String(length=64), nullable=False),
    sa.Column('recipe_version', sa.String(length=16), nullable=False),
    sa.Column('recipe', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('manufacturing_rules_version', sa.String(length=64), nullable=False),
    sa.Column('validation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('validation_passed', sa.Boolean(), nullable=False),
    sa.Column('identity_verified', sa.Boolean(), nullable=False),
    sa.Column('manufacturing_score', sa.Float(), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=False),
    sa.Column('edit_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['design_id'], ['designs.id'], ),
    sa.ForeignKeyConstraint(['parent_version_id'], ['design_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('design_id', 'version_number')
    )
    op.create_index(op.f('ix_design_versions_design_id'), 'design_versions', ['design_id'], unique=False)
    op.create_table('customer_approvals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('design_version_id', sa.UUID(), nullable=False),
    sa.Column('confirmed_text', sa.Text(), nullable=False),
    sa.Column('confirmation_statement', sa.Text(), nullable=False),
    sa.Column('source_text_sha256', sa.String(length=64), nullable=False),
    sa.Column('geometry_hash', sa.String(length=64), nullable=False),
    sa.Column('approval_hash', sa.String(length=64), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_by', sa.String(length=120), nullable=False),
    sa.Column('approval_method', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['design_version_id'], ['design_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('approval_hash'),
    sa.UniqueConstraint('design_version_id')
    )
    op.create_table('design_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=True),
    sa.Column('design_id', sa.UUID(), nullable=True),
    sa.Column('version_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('actor_type', sa.String(length=24), nullable=False),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['design_id'], ['designs.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['design_requests.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['design_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_design_events_design_id'), 'design_events', ['design_id'], unique=False)
    op.create_index(op.f('ix_design_events_request_id'), 'design_events', ['request_id'], unique=False)
    op.create_table('exports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('format', sa.String(length=8), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('width_mm', sa.Float(), nullable=False),
    sa.Column('height_mm', sa.Float(), nullable=False),
    sa.Column('units', sa.String(length=8), nullable=False),
    sa.Column('validation_rules_version', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['design_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('manufacturing_validation_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=True),
    sa.Column('candidate_id', sa.UUID(), nullable=True),
    sa.Column('rules_profile', sa.String(length=64), nullable=False),
    sa.Column('rules_version', sa.String(length=64), nullable=False),
    sa.Column('rules_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('violations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['design_candidates.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['design_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # --- DB-level immutability (ADR-0001) ---
    # design_versions: history is append-only. The only legal UPDATE is the
    # status transition UNAPPROVED -> APPROVED_LOCKED (plus updated_at).
    op.execute(
        """
        CREATE OR REPLACE FUNCTION enforce_design_version_immutability()
        RETURNS trigger AS $$
        BEGIN
            IF OLD.immutable_source_text IS DISTINCT FROM NEW.immutable_source_text
               OR OLD.source_text_sha256 IS DISTINCT FROM NEW.source_text_sha256
               OR OLD.geometry_wkt IS DISTINCT FROM NEW.geometry_wkt
               OR OLD.geometry_hash IS DISTINCT FROM NEW.geometry_hash
               OR OLD.version_number IS DISTINCT FROM NEW.version_number
               OR OLD.design_id IS DISTINCT FROM NEW.design_id
               OR OLD.parent_version_id IS DISTINCT FROM NEW.parent_version_id
               OR OLD.recipe IS DISTINCT FROM NEW.recipe
               OR OLD.recipe_id IS DISTINCT FROM NEW.recipe_id
               OR OLD.font_id IS DISTINCT FROM NEW.font_id
               OR OLD.font_version IS DISTINCT FROM NEW.font_version
               OR OLD.validation IS DISTINCT FROM NEW.validation
               OR OLD.created_by IS DISTINCT FROM NEW.created_by
               OR OLD.created_at IS DISTINCT FROM NEW.created_at THEN
                RAISE EXCEPTION 'design_versions rows are immutable (ADR-0001)';
            END IF;
            IF OLD.status IS DISTINCT FROM NEW.status
               AND NOT (OLD.status = 'UNAPPROVED' AND NEW.status = 'APPROVED_LOCKED') THEN
                RAISE EXCEPTION 'illegal design_version status transition % -> %',
                    OLD.status, NEW.status;
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;

        CREATE TRIGGER trg_design_version_immutability
        BEFORE UPDATE ON design_versions
        FOR EACH ROW EXECUTE FUNCTION enforce_design_version_immutability();

        CREATE OR REPLACE FUNCTION forbid_delete() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION '% rows are append-only (ADR-0001)', TG_TABLE_NAME;
        END;
        $$ LANGUAGE plpgsql;

        CREATE TRIGGER trg_design_version_no_delete
        BEFORE DELETE ON design_versions
        FOR EACH ROW EXECUTE FUNCTION forbid_delete();

        -- customer_approvals: hash/text frozen; only ACTIVE -> INVALIDATED.
        CREATE OR REPLACE FUNCTION enforce_approval_immutability()
        RETURNS trigger AS $$
        BEGIN
            IF OLD.approval_hash IS DISTINCT FROM NEW.approval_hash
               OR OLD.design_version_id IS DISTINCT FROM NEW.design_version_id
               OR OLD.confirmed_text IS DISTINCT FROM NEW.confirmed_text
               OR OLD.source_text_sha256 IS DISTINCT FROM NEW.source_text_sha256
               OR OLD.geometry_hash IS DISTINCT FROM NEW.geometry_hash
               OR OLD.approved_at IS DISTINCT FROM NEW.approved_at THEN
                RAISE EXCEPTION 'customer_approvals rows are immutable (ADR-0001)';
            END IF;
            IF OLD.status IS DISTINCT FROM NEW.status
               AND NOT (OLD.status = 'ACTIVE' AND NEW.status = 'INVALIDATED') THEN
                RAISE EXCEPTION 'illegal approval status transition % -> %',
                    OLD.status, NEW.status;
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;

        CREATE TRIGGER trg_approval_immutability
        BEFORE UPDATE ON customer_approvals
        FOR EACH ROW EXECUTE FUNCTION enforce_approval_immutability();

        CREATE TRIGGER trg_approval_no_delete
        BEFORE DELETE ON customer_approvals
        FOR EACH ROW EXECUTE FUNCTION forbid_delete();

        -- design_events: append-only audit log.
        CREATE TRIGGER trg_events_no_delete
        BEFORE DELETE ON design_events
        FOR EACH ROW EXECUTE FUNCTION forbid_delete();

        CREATE OR REPLACE FUNCTION forbid_update() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION '% rows are append-only (ADR-0001)', TG_TABLE_NAME;
        END;
        $$ LANGUAGE plpgsql;

        CREATE TRIGGER trg_events_no_update
        BEFORE UPDATE ON design_events
        FOR EACH ROW EXECUTE FUNCTION forbid_update();

        CREATE TRIGGER trg_exports_no_update
        BEFORE UPDATE ON exports
        FOR EACH ROW EXECUTE FUNCTION forbid_update();

        CREATE TRIGGER trg_exports_no_delete
        BEFORE DELETE ON exports
        FOR EACH ROW EXECUTE FUNCTION forbid_delete();
        """
    )


def downgrade() -> None:
    op.execute(
        """
        DROP TRIGGER IF EXISTS trg_design_version_immutability ON design_versions;
        DROP TRIGGER IF EXISTS trg_design_version_no_delete ON design_versions;
        DROP TRIGGER IF EXISTS trg_approval_immutability ON customer_approvals;
        DROP TRIGGER IF EXISTS trg_approval_no_delete ON customer_approvals;
        DROP TRIGGER IF EXISTS trg_events_no_delete ON design_events;
        DROP TRIGGER IF EXISTS trg_events_no_update ON design_events;
        DROP TRIGGER IF EXISTS trg_exports_no_update ON exports;
        DROP TRIGGER IF EXISTS trg_exports_no_delete ON exports;
        DROP FUNCTION IF EXISTS enforce_design_version_immutability();
        DROP FUNCTION IF EXISTS enforce_approval_immutability();
        DROP FUNCTION IF EXISTS forbid_delete();
        DROP FUNCTION IF EXISTS forbid_update();
        """
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('manufacturing_validation_runs')
    op.drop_table('exports')
    op.drop_index(op.f('ix_design_events_request_id'), table_name='design_events')
    op.drop_index(op.f('ix_design_events_design_id'), table_name='design_events')
    op.drop_table('design_events')
    op.drop_table('customer_approvals')
    op.drop_index(op.f('ix_design_versions_design_id'), table_name='design_versions')
    op.drop_table('design_versions')
    op.drop_table('designs')
    op.drop_index(op.f('ix_design_candidates_request_id'), table_name='design_candidates')
    op.drop_table('design_candidates')
    op.drop_table('font_references')
    op.drop_table('design_requests')
    # ### end Alembic commands ###
